FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/server/package.json apps/server/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/env/package.json packages/env/package.json
COPY packages/config/package.json packages/config/package.json

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev:server"]v